### ISSUE TITLE
 Multi-Module Spring Boot Application with Gradle not work IntelliJ

### ISSUE THREAD

**Issue by jhovannycanas** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#14]
cordial greetings
when I try to use the api library in the product-service microservice using IntelliJ, it says that the project is not found, I followed the instructions in the book but the project is not found.

Caused by: org.gradle.api.UnknownProjectException: Project with path ':api' could not be found in root project 'product-service'.

this is the settigs.gradle

include ':microservices:product-service'
include ':microservices:review-service'
include ':microservices:recommendation-service'
include ':microservices:product-composite-service'
include ':api'
include ':util'

this is the dependency call in product-service

dependencies {
	compile project(':api')
	implementation project(':util')
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
}

**Comment by Miles-Ahead-Digital** [comment]
This works:


dependencies {
	implementation project(':api')
	implementation project(':util')
	implementation('org.springframework.boot:spring-boot-starter-actuator')
	implementation('org.springframework.boot:spring-boot-starter-webflux')
....

**Comment by magnus-larsson** [comment]
Hello and thanks for the question!

I guess that IntelliJ has not been able to resolve the dependencies between the product-service microservice.
Can you follow the instructions in my reply in issue #13 to ensure that you instruct IntelliJ to setup dependencies correctly?

Please, let me know if this works or if you run into any problems!

**Comment by masoud-moghini** [comment]
same problem with eclipse ,also applied @Miles-Ahead-Digital solution ,which is original code in Chapter3 forlder, didn't solve the issue 
`> Project with path ':api' could not be found in root project 'product-services'.
`

**Comment by jhovannycanas** [comment]
tks, Magnus
