### ISSUE TITLE
Chapter 13 - Resilience4J with SpringBoot 2.4.0

### ISSUE THREAD

**Issue by ClimberBear** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#21]
Hi,

I have suffered the bug you reported about incompatibility between Resilience4J 1.6.1 and SpringBoot 2.4.0

[The Reactor based RetryOperator uses a deprecated method that is removed in Reactor 3.4.0 used by Spring Boot 2.4.0](https://github.com/resilience4j/resilience4j/issues/1233)

I'm trying to update to version 1.7.0. For this, I have tried to update my build.gradle to

```
// ... Not relevant
ext {
   resilience4jVersion = "1.7.0"
}
dependencies {
// ... Not relevante
	implementation("io.github.resilience4j:resilience4j-spring-boot2:${resilience4jVersion}")
	implementation("io.github.resilience4j:resilience4j-reactor:${resilience4jVersion}")
}
```

But then, when I try gradle build, I the test phase, I get the error
```
Caused by: java.lang.ClassNotFoundException: io.github.resilience4j.core.ContextAwareScheduledThreadPoolExecutor
```

Have you got this working? Which are the right dependencies?

BTW, I have also tried (with the same result) adding all dependencies, as

```
  implementation("io.github.resilience4j:resilience4j-spring-boot2:${resilience4jVersion}")
  implementation("io.github.resilience4j:resilience4j-reactor:${resilience4jVersion}")
  implementation "io.github.resilience4j:resilience4j-circuitbreaker:${resilience4jVersion}"
  implementation "io.github.resilience4j:resilience4j-ratelimiter:${resilience4jVersion}"
  implementation "io.github.resilience4j:resilience4j-retry:${resilience4jVersion}"
  implementation "io.github.resilience4j:resilience4j-bulkhead:${resilience4jVersion}"
  implementation "io.github.resilience4j:resilience4j-cache:${resilience4jVersion}"
  implementation "io.github.resilience4j:resilience4j-timelimiter:${resilience4jVersion}"
	
```

**Comment by ClimberBear** [comment]
Hi,

I found this issue with a workaround of the problem, making possible to use version 1.7.0 of relience4j. Testing now.

https://github.com/resilience4j/resilience4j/issues/1361

**Comment by magnus-larsson** [comment]
Hello!

Sorry for not responding earlier, but I have been very busy lately finishing [the 2'nd edition of my book](https://www.amazon.com/Microservices-Spring-Boot-Cloud-microservices/dp/1801072973).  
(I have also written a [blog post on the updates in the 2nd edition](https://callistaenterprise.se/blogg/teknik/2021/08/09/microservices-book-2nd-edition-updates/), if you are interested)

Yes, I'm using Resilience4J 1.7.0 and SpringBoot 2.5.2 in the 2nd edition!
Please take a look at https://github.com/PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E/blob/main/Chapter13/microservices/product-composite-service/build.gradle.

Hope it helps!

Please reopen the issue if you have further questions,
Magnus.

**Comment by ClimberBear** [comment]
Congrats!

It's a great notice the book success!

Do you know if packt let me download the new edition if I own the 1st one?

In any case, thank you. I will continue recommending it to my colleagues.

Regards

Jose Manuel Albarrán

b-Thinking software

+34 616 968 262

***@***.***


________________________________

**Comment by craigwarsaw** [comment]
Hello Magnus,

The link to your blog post gives me a 404.
Thanks for your hard work keeping the repo up to date.


Craig Warsaw, Chief Engineer

w (301) 543-6510 | c (410) 336-7702 | ***@***.******@***.***>

CACI/NSIS/ASG/NS/Critical Insight Solutions | www.caci.com<http://www.caci.com/>

formerly Next Century Corporation

________________________________

**Comment by magnus-larsson** [comment]
Hello Craig, thanks for pointing out the invalid link!

The link to the blog post is now corrected!
