### ISSUE TITLE
Proposal for new version of the book: End2End Tests with Cucumber instead of the shell scripts..

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#23]
Hi,
I would be great if the End2End shell scripts would be replaced by a End2End (BDD) Testing Framework. I would prefer Cucumber. A good example is here:

https://thepracticaldeveloper.com/cucumber-guide-2-cucumber-http-api/

Best regards
Stefan

**Comment by magnus-larsson** [comment]
Hello Stefan!

Sorry for not responding earlier, but I have been very busy lately finishing [the 2'nd edition of my book](https://www.amazon.com/Microservices-Spring-Boot-Cloud-microservices/dp/1801072973).  
(I have also written a [blog post on the updates in the 2nd edition](https://callistaenterprise.se/blogg/teknik/2021/08/09/microservices-book-2nd-edition-updates/) if you are interested)

Yes, I have thought about using a separate testing framework, such as Cucumber or Postman together with Newman.
But I decided to stay using curl in the already existing bash-script, (the bash-script does more than verifying the APIs using curl, so I need to keep it anyhow). The main reason for keep using curl is that curl is already used to test the APIs manually. To minimize the number of tools used in the book, I simply reuse the curl requests from the manual tests in the bash-script to automate the verifications.

But maybe I'll write a blog post in the future explaining how to use a proper test framework for the APIs used in the book :-)

Regards,
Magnus.
