### ISSUE TITLE
Chapter 3: Implementing Our API (Step 7): gradlew build ->  Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

### ISSUE THREAD

**Issue by CPassarge** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#26]
Not exactly an issue, but I thought this might help some people…

On Win 10, executing the following command:

`gradlew build
`
Yields this result/error:

`Could not initialize class org.codehaus.groovy.runtime.InvokerHelper`

This can be fixed by changing the **gradle-wrapper.properties** as follows:

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-bin.zip`
To:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip`

(The file can be found here: ../Chapter03/2-basic-rest-services/gradle/wrapper/gradle-wrapper.properties)

Just for reference, the configuration I used is:
```
>java --version
java 15.0.2 2021-01-19

>spring --version
Spring CLI v2.5.1

>gradle --version
Gradle 7.1
Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7-27)
OS:           Windows 10 10.0 amd64
```

**Comment by ManikandanKurup-Packt** [comment]
Hi @CPassarge 
Thanks for the solution. I have added a README for the same in the folder.
