### ISSUE TITLE
review-service: DB requests run under wrong thread pool

### ISSUE THREAD

**Issue by jaimenavarro** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#3]
Hi Magnus, 

Sorry for bothering you, I'm reading your book, by the way it's a good one ;), right now I'm on chapter 7 and I realised that there is an improvement that I guess could be added to this code.

It seems to be that in **review-service** DB request doesn't run under blocking thread pool that you created, this means that you could run out of non-blocking threads which are in charge of receiving incoming requests.

I'm not an expert of Spring Reactive Framework, but after a small test, it seems that this could be fixed starting the Flux stream before sending any request to the DB.

Here a code example:
/review-service/src/main/java/se/magnus/microservices/core/review/services/ReviewServiceImpl.java
`private Flux<Review> asyncFlux(int productId) {
        return Flux.just(productId)
                .subscribeOn(scheduler)
                .map( id -> getByProductId(id) )
                .flatMap(Flux::fromIterable);
    }
`

Thanks a lot for the book. I'm learning about this topic so maybe what I wrote above could be improved.

**Comment by magnus-larsson** [comment]
Hello and thanks for reporting this issue!

You are totally right, this call will make the database request run on the request thread instead of running on a thread from the thread pool:

https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud/blob/b6b131cdf25b47029ebeac2e4168ee363114ced2/Chapter07/microservices/review-service/src/main/java/se/magnus/microservices/core/review/services/ReviewServiceImpl.java#L62

I have missed deferring the execution to the scheduler, as you pointed out.

I'll take a look at your code and see if I can simplify it a bit :-)

Regards,
Magnus.

**Comment by magnus-larsson** [comment]
The bug can be observed by running the test getReviewsByProductId in ReviewServiceApplicationTests with the log level set to debug.

The debug log output from the review service implementation:

https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud/blob/b6b131cdf25b47029ebeac2e4168ee363114ced2/Chapter07/microservices/review-service/src/main/java/se/magnus/microservices/core/review/services/ReviewServiceImpl.java#L71

...should report usage of a thread from the thread pool, but from the log output it can be seen that the HTTP thread (`ctor-http-nio-6` in the log output below) is used instead, e.g.:

`2020-03-07 13:52:47.469 DEBUG [-,7d8821a1b4907f4e,7d8821a1b4907f4e,false] 99896 --- [ctor-http-nio-6] s.m.m.c.r.services.ReviewServiceImpl     : Response size: 3
`

**Comment by magnus-larsson** [comment]
The helper method `asyncFlux` now defers execution to the thread pool:

https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud/blob/fe38b1dcbe7efca77fdc9c0a999581a8ec066d46/Chapter07/microservices/review-service/src/main/java/se/magnus/microservices/core/review/services/ReviewServiceImpl.java#L91-L93

The call to the helper method `asyncFlux` now looks like:

https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud/blob/fe38b1dcbe7efca77fdc9c0a999581a8ec066d46/Chapter07/microservices/review-service/src/main/java/se/magnus/microservices/core/review/services/ReviewServiceImpl.java#L68

Log output from the test `getReviewsByProductId` in `ReviewServiceApplicationTests` now shows that the database search in the method  `getReviews` actually executes in a thread from the thread pool (thread named `pool-1-thread-1 `in the samples log output below):

`2020-03-07 16:26:26.241 DEBUG [-,7af91123d08c704c,630131ba8ba2bf22,false] 5537 --- [pool-1-thread-1] s.m.m.c.r.services.ReviewServiceImpl     : getReviews: response size: 3
`
