### ISSUE TITLE
debug individual microservices outside of docker

### ISSUE THREAD

**Issue by datasmithadvtech** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#4]
My windows desktop , server 2012 R2, doesn't support containers, so i want to debug individual microservices within intellij outside of docker.

jars are not created for individual microservices, such as review

I am not familiar with gradle, however, i can if i convert to maven project i can  create the missing jars

**Comment by magnus-larsson** [comment]
If you are using Intellij, it should not be a problem to debug individual microservices outside of Docker!

Simply import the desired chapter from the book into Intellij and it will detect that it is using Gradle and set up everything for you.

Then you can start, for example, the review service in debug mode and catch breakpoints as pointed out by the provided screenshot.

![Screenshot 2020-04-26 at 18 23 59](https://user-images.githubusercontent.com/1313727/80313531-a693f480-87eb-11ea-931c-2622b4894166.png)

Does that answer your question?

**Comment by magnus-larsson** [comment]
The issuer has confirmed via email that it is ok to close this issue.
