### ISSUE TITLE
OS required needs to support Docker

### ISSUE THREAD

**Issue by datasmithadvtech** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#5]
Windows 10, or Windows Server 2016+

Docker does not run on Windows Server 2012

**Comment by magnus-larsson** [comment]
I'm not sure I understand this issue.

It is true that Docker does not run on Windows Server 2012, but I'm not sure how it becomes an issue for this GitHub project?

Can you explain a bit more about what you expect this issue to solve?
